In [2]:
import pandas as pd

dataset = pd.read_csv("/Users/nicoletimko/Desktop/capstone_victimization/full_dataset/full_data.csv")

In [3]:
display(dataset)

,college_status_1997_01,college_status_1997_02,college_status_1997_03,college_status_1997_04,college_status_1997_05,college_status_1997_06,college_status_1997_07,college_status_1997_08,college_status_1997_09,college_status_1997_10,...,lived_with_both_bio_parents_at_birth,first_college_year,first_college_month,age_at_first_college,first_college_time,first_enroll_source,college_history,n_obs_17_20,timely_college,timely_category
0,-4,-4,-4,-4,-4,-4,1,1,1,1,...,-4,1999.0,8.0,17.0,23996.0,other month,Enrolled,48,1.0,Timely enrollment
1,-4,-4,-4,-4,1,1,1,1,1,1,...,1,2000.0,8.0,18.0,24008.0,other month,Enrolled,48,1.0,Timely enrollment
2,-4,-4,-4,1,1,1,1,1,1,1,...,-4,2001.0,6.0,17.0,24018.0,other month,Enrolled,48,1.0,Timely enrollment
3,-4,1,1,1,1,1,1,1,1,1,...,1,2002.0,1.0,20.0,24025.0,Jan/Feb/Sep,Enrolled,48,1.0,Timely enrollment
4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,...,-4,NaN,NaN,NaN,NaN,NaN,Never observed enrolled,48,0.0,Never observed enrolled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8979,-4,-4,-4,-4,-4,-4,-4,1,1,1,...,1,NaN,NaN,NaN,NaN,NaN,Never observed enrolled,43,0.0,Never observed enrolled
8980,-4,-4,-4,-4,-4,1,1,1,1,1,...,-4,2005.0,10.0,21.0,24070.0,other month,Enrolled,48,0.0,"Enrolled, but not timely"
8981,-4,-4,-4,-4,-4,1,1,1,1,1,...,-4,1998.0,8.0,18.0,23984.0,other month,Enrolled,48,1.0,Timely enrollment
8982,-4,-4,-4,-4,-4,1,1,1,1,1,...,-4,1999.0,3.0,18.0,23991.0,other month,Enrolled,48,1.0,Timely enrollment
8983,-4,-4,-4,-4,-4,1,1,1,1,1,...,-4,2000.0,4.0,18.0,24004.0,other month,Enrolled,48,1.0,Timely enrollment

In [4]:
victim_cols = ["violent_victim_2002", "violent_victim_2007", "violent_victim_2008", "violent_victim_2009", "violent_victim_2013"]

victim_data = dataset[victim_cols].apply(pd.to_numeric, errors="coerce")
reported_yes = (victim_data == 1).any(axis=1)
has_response = ((victim_data == 0) | (victim_data == 1)).any(axis=1)

dataset["victim_ever"] = pd.Series(pd.NA, index=dataset.index, dtype="Int64") # fills everything NA first
# so if not a valid response or 1 then will stay NA
dataset.loc[has_response, "victim_ever"] = 0
dataset.loc[reported_yes, "victim_ever"] = 1

/var/folders/kg/r8nr__jd2v39p4hjcq48qqh40000gn/T/ipykernel_35661/4016411155.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset["victim_ever"] = pd.Series(pd.NA, index=dataset.index, dtype="Int64") # fills everything NA first

In [5]:
victim_age_cols = [
    "age_at_violent_victimization_2002",
    "age_at_violent_victimization_2007",
    "age_at_violent_victimization_2008",
    "age_at_violent_victimization_2009",
    "age_at_violent_victimization_2013"
]

def collect_victimization_ages(row):
    ages = []

    for col in victim_age_cols:
        age = row[col]

        # Keep valid reported ages only
        if pd.notna(age) and age > 0:
            ages.append(int(age))

    return ages


dataset["victimization_ages"] = dataset.apply(
    collect_victimization_ages,
    axis=1
)

/var/folders/kg/r8nr__jd2v39p4hjcq48qqh40000gn/T/ipykernel_35661/1667145520.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset["victimization_ages"] = dataset.apply(

In [6]:
dataset["ever_enrolled"] = ((dataset["college_history"] == "Enrolled") | (dataset["college_history"] == "Grad program only")).astype(int)

/var/folders/kg/r8nr__jd2v39p4hjcq48qqh40000gn/T/ipykernel_35661/4157731737.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset["ever_enrolled"] = ((dataset["college_history"] == "Enrolled") | (dataset["college_history"] == "Grad program only")).astype(int)

Did we want grad program?

In [7]:
dataset["college_history"].value_counts()

college_history
Enrolled                   5918
Never observed enrolled    3059
Grad program only             7
Name: count, dtype: int64

In [8]:
dataset

,college_status_1997_01,college_status_1997_02,college_status_1997_03,college_status_1997_04,college_status_1997_05,college_status_1997_06,college_status_1997_07,college_status_1997_08,college_status_1997_09,college_status_1997_10,...,age_at_first_college,first_college_time,first_enroll_source,college_history,n_obs_17_20,timely_college,timely_category,victim_ever,victimization_ages,ever_enrolled
0,-4,-4,-4,-4,-4,-4,1,1,1,1,...,17.0,23996.0,other month,Enrolled,48,1.0,Timely enrollment,0,[],1
1,-4,-4,-4,-4,1,1,1,1,1,1,...,18.0,24008.0,other month,Enrolled,48,1.0,Timely enrollment,0,[],1
2,-4,-4,-4,1,1,1,1,1,1,1,...,17.0,24018.0,other month,Enrolled,48,1.0,Timely enrollment,0,[],1
3,-4,1,1,1,1,1,1,1,1,1,...,20.0,24025.0,Jan/Feb/Sep,Enrolled,48,1.0,Timely enrollment,0,[],1
4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,...,NaN,NaN,NaN,Never observed enrolled,48,0.0,Never observed enrolled,1,[20],0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8979,-4,-4,-4,-4,-4,-4,-4,1,1,1,...,NaN,NaN,NaN,Never observed enrolled,43,0.0,Never observed enrolled,0,[],0
8980,-4,-4,-4,-4,-4,1,1,1,1,1,...,21.0,24070.0,other month,Enrolled,48,0.0,"Enrolled, but not timely",0,[],1
8981,-4,-4,-4,-4,-4,1,1,1,1,1,...,18.0,23984.0,other month,Enrolled,48,1.0,Timely enrollment,0,[],1
8982,-4,-4,-4,-4,-4,1,1,1,1,1,...,18.0,23991.0,other month,Enrolled,48,1.0,Timely enrollment,0,[],1
8983,-4,-4,-4,-4,-4,1,1,1,1,1,...,18.0,24004.0,other month,Enrolled,48,1.0,Timely enrollment,1,[16],1

In [ ]:
def create_outcome(row):
    ages = row["victimization_ages"]
    enrolled = row["ever_enrolled"]
    enrollment_age = row["age_at_first_college"]
    victim_ever = row["victim_ever"]

    # Missing victimization information
    if pd.isna(victim_ever):
        return pd.Series({
            "Y": pd.NA,
            "prior_victimization": pd.NA,
            "same_age_as_enrollment": pd.NA,

        })

    # Never reported victimization
    if victim_ever == 0:
        return pd.Series({
            "Y": 0,
            "prior_victimization": 0,
            "same_age_as_enrollment": 0,

        })

    # Make sure victimization ages are stored as a list
    if not isinstance(ages, list):
        valid_ages = []

    else:
        valid_ages = [
            age for age in ages
            if pd.notna(age) and age > 0
        ]

    # Reported victimization, but no valid age is available
    if len(valid_ages) == 0:
        return pd.Series({
            "Y": pd.NA,
            "prior_victimization": pd.NA,
            "same_age_as_enrollment": pd.NA,
        })

    # Missing college-enrollment status
    if pd.isna(enrolled):
        return pd.Series({
            "Y": pd.NA,
            "prior_victimization": pd.NA,
            "same_age_as_enrollment": pd.NA,
        })

    # --------------------------------------------------
    # Never enrolled
    # --------------------------------------------------

    if enrolled == 0:

        # Victimized during the outcome period
        during_17_24 = any(
            17 <= age <= 24
            for age in valid_ages
        )

        # For never-enrolled people, prior means before age 17
        before_17 = any(
            age < 17
            for age in valid_ages
        )

        return pd.Series({
            "Y": int(during_17_24),
            "prior_victimization": int(before_17),
            "same_age_as_enrollment": 0,
        })

    # --------------------------------------------------
    # Enrolled
    # --------------------------------------------------

    # Enrolled, but first enrollment age is unavailable
    if pd.isna(enrollment_age):
        return pd.Series({
            "Y": pd.NA,
            "prior_victimization": pd.NA,
            "same_age_as_enrollment": pd.NA,
        })

    # Victimization before first enrollment
    prior = any(
        age < enrollment_age
        for age in valid_ages
    )

    # Victimization at the same age as first enrollment
    same_age = any(
        age == enrollment_age
        for age in valid_ages
    )

    # Victimization after enrollment during ages 17–24
    after_enrollment_17_24 = any(
        age > enrollment_age
        and 17 <= age <= 24
        for age in valid_ages
    )

    # Victimization after both enrollment and age 24
    after_enrollment_and_24 = any(
        age > enrollment_age
        and age > 24
        for age in valid_ages
    )

    # Definite qualifying outcome
    if after_enrollment_17_24:
        outcome = 1

    # Victimization only known to be at the same age
    elif same_age:
        outcome = pd.NA

    else:
        outcome = 0

    return pd.Series({
        "Y": outcome,
        "prior_victimization": int(prior),
        "same_age_as_enrollment": int(same_age),
    })

In [10]:
outcome_columns = [
    "Y",
    "prior_victimization",
    "same_age_as_enrollment",
]

dataset[outcome_columns] = dataset.apply(
    create_outcome,
    axis=1
)

for col in outcome_columns:
    dataset[col] = dataset[col].astype("Int64")

/var/folders/kg/r8nr__jd2v39p4hjcq48qqh40000gn/T/ipykernel_35661/2438251932.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  dataset[outcome_columns] = dataset.apply(

In [11]:
display(dataset)

,college_status_1997_01,college_status_1997_02,college_status_1997_03,college_status_1997_04,college_status_1997_05,college_status_1997_06,college_status_1997_07,college_status_1997_08,college_status_1997_09,college_status_1997_10,...,college_history,n_obs_17_20,timely_college,timely_category,victim_ever,victimization_ages,ever_enrolled,Y,prior_victimization,same_age_as_enrollment
0,-4,-4,-4,-4,-4,-4,1,1,1,1,...,Enrolled,48,1.0,Timely enrollment,0,[],1,0,0,0
1,-4,-4,-4,-4,1,1,1,1,1,1,...,Enrolled,48,1.0,Timely enrollment,0,[],1,0,0,0
2,-4,-4,-4,1,1,1,1,1,1,1,...,Enrolled,48,1.0,Timely enrollment,0,[],1,0,0,0
3,-4,1,1,1,1,1,1,1,1,1,...,Enrolled,48,1.0,Timely enrollment,0,[],1,0,0,0
4,-4,-4,-4,-4,-4,-4,-4,-4,-4,-4,...,Never observed enrolled,48,0.0,Never observed enrolled,1,[20],0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8979,-4,-4,-4,-4,-4,-4,-4,1,1,1,...,Never observed enrolled,43,0.0,Never observed enrolled,0,[],0,0,0,0
8980,-4,-4,-4,-4,-4,1,1,1,1,1,...,Enrolled,48,0.0,"Enrolled, but not timely",0,[],1,0,0,0
8981,-4,-4,-4,-4,-4,1,1,1,1,1,...,Enrolled,48,1.0,Timely enrollment,0,[],1,0,0,0
8982,-4,-4,-4,-4,-4,1,1,1,1,1,...,Enrolled,48,1.0,Timely enrollment,0,[],1,0,0,0
8983,-4,-4,-4,-4,-4,1,1,1,1,1,...,Enrolled,48,1.0,Timely enrollment,1,[16],1,0,1,0

In [12]:
dataset.to_csv("/Users/nicoletimko/Desktop/capstone_victimization/full_dataset/data_with_Y.csv")